#!/bin/bash

# Author: https://github.com/marblenix/

# Running this script implies that you agree to all applicable terms and
# conditions found on the Adobe website. I take no responsibility for any
# damage that may occur by running this script. I am in no way affiliated
# with Adobe or it's products or partners. No ownership of any of the
# aforementioned is implied.

if [[ "$EUID" == 0 ]]; then
    echo "THIS SCRIPT MUST _NEVER_ BE RUN AS ROOT"
    exit 1
fi

if [[ "$#" -lt 1 ]]; then
    echo "Usage: $(basename "$0") /path/to/install_flash_player_osx.dmg"
    exit 1
fi

tmp_folder="/tmp/$(basename "$0")_$$"
firefox_profile="$HOME/Library/Application Support/Firefox"
installer_dmg="$1"

cleanup() {
    # Only cleanup if the directory exists and begins with "/tmp/"
    if test -d "$tmp_folder"; then
        if [[ "$tmp_folder" = /tmp/* ]]; then
            echo "Removing $tmp_folder"
            rm -rf "$tmp_folder"
        fi
    fi
}

trap cleanup INT TERM EXIT

if ! test -f "$installer_dmg"; then
    echo "$installer_dmg is not a regular file."
    exit 1
fi

mkdir -p "$tmp_folder"
cd "$tmp_folder" || exit 100

echo "Mounting installer DMG..."
hdiutil attach "$installer_dmg" -mountpoint /Volumes/Flash -nobrowse -noautoopen &> /dev/null
echo "Copying resources..."
cp "/Volumes/Flash/Install Adobe Flash Player.app/Contents/Resources/Adobe Flash Player.pkg" "$tmp_folder"
echo "Unmounting installer DMG..."
hdiutil detach /Volumes/Flash &> /dev/null

echo "Extracting blobs..."
tar xzf "$tmp_folder/Adobe Flash Player.pkg"
tar xzf "$tmp_folder/AdobeFlashPlayerComponent.pkg/Scripts"
tar xzf "$tmp_folder/AdobeFlashPlayerComponent.pkg/Payload"
# The following is a magical script that runs a blob that I do not understand.
# The only thing it appears to do is unzip the Flash Player.plugin.lzma file.
./postinstall ./ ./ ./

profiles=($(grep Path "$firefox_profile/profiles.ini"))
# Expected format for $profiles: Path=Profiles/io1znthy.default
counter=0
for (( i = 0; i < ${#profiles[@]}; i++ )) do
    profile_path="$(echo "${profiles[$i]}" | awk -F'=' '{print $2}')"
    # Expected format for $profile_path: Profiles/bolznthy.default
    flashlight_archive_path="$firefox_profile/$profile_path/plugins"
    flashlight_flash_plugin_path="$flashlight_archive_path"

    if [ -d "$flashlight_archive_path" ]; then
        echo "Found compatible flashlight archive path in: $flashlight_archive_path"
        let 'counter = counter + 1'
    else
        continue
    fi

    if test -d "$flashlight_flash_plugin_path"; then
        echo "Removing old flash plugin."
        # Originally this would move the flash pugin path to the .Trash file.
        # But for some reason it introduced a bug where the latest version would
        # not be installed. TODO: Change this line to remove the `rm` command
        rm -rf "$flashlight_flash_plugin_path/Flash Player.plugin"
        rm -f "$flashlight_flash_plugin_path/flashplayer.xpt"
    fi

    mkdir -p "$flashlight_flash_plugin_path"
    echo "Installing flash plugin."
    cp -R "$tmp_folder/Library/Internet Plug-Ins/Flash Player.plugin" "$flashlight_flash_plugin_path"
    cp "$tmp_folder/Library/Internet Plug-Ins/flashplayer.xpt" "$flashlight_flash_plugin_path"
done

echo
if [[ $counter == 0 ]]; then
    echo "Did not find flashinator plugin directory."
    echo "Do you have the addon Flasinator installed?"
    echo "Have you restarted firefox at least once after installing flashinator?"
else
    echo "This script finished successfully."
fi
